sudo: required
services: 
  - docker

before_install:
  - docker build -t jayboo876/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true jayboo876/react-test npm test

after_success:
  - docker build -t jayboo876/multi-client ./client
  - docker build -t jayboo876/multi-server ./server
  - docker build -t jayboo876/multi-nginx ./nginx
  - docker build -t jayboo876/multi-worker ./worker
