sudo: required
services: 
  - docker

before_install:
  - docker build -t jayboo876/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jayboo876/react-test npm test

# Build Containers if tests are successful
after_success:
  - docker build -t jayboo876/multi-client ./client
  - docker build -t jayboo876/multi-server ./server
  - docker build -t jayboo876/multi-nginx ./nginx
  - docker build -t jayboo876/multi-worker ./worker
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push jayboo876/multi-client
  - docker push jayboo876/multi-server
  - docker push jayboo876/multi-nginx
  - docker push jayboo876/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-575311930892'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY